version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.17.2
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'Elk@2024'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.17.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  vector:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml  
    ports:
      - 80:8888

volumes:
  elasticsearch-data:
