version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'Elk@2025'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:Elk@2025 http://elasticsearch:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  vector:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml  
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 8888:80


# volumes:
#   elasticsearch-data:
